# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: postgresql
  encoding: unicode
  database: feedkraft_development
  username: postgres
  password:
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: test_development
  username: postgres
  password:
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: feedkraft_production
  username: www-data
  password:
  pool: 5
  timeout: 5000

development-sqlite3:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test-sqlite3:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production-sqlite3:
  adapter: sqlite3
  database: production.sqlite3
  pool: 5
  timeout: 5000

